name: Testing

on:
  push:
    branches: [ main ]
    paths-ignore:
      - 'README.md'
  pull_request:
    branches: [ main ]
    paths-ignore:
      - 'README.md'

jobs:
  test:
    continue-on-error: true
    strategy:
      matrix:
        os: [ macos-latest, ubuntu-latest ]
        cxx: [ g++, clang++ ]
        stdlib: [ libstdc++, libc++ ]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v4
    - name: Install GNU Getopt on macOS
      if: runner.os == 'macOS'
      run: brew install gnu-getopt
    - name: configure on macOS
      if: runner.os == 'macOS'
      run: ./configure --with-cxx=${{ matrix.cxx }}
    - name: configure on Other OS
      if: runner.os != 'macOS'
      run: ./configure --with-cxx=${{ matrix.cxx }} --with-cxx-standard-library=${{ matrix.stdlib }}
    - name: build
      run: make
    - name: check
      run: make check
