name: Testing

on:
  push:
    branches: [ main ]
    paths-ignore:
      - 'README.md'
  pull_request:
    branches: [ main ]
    paths-ignore:
      - 'README.md'

jobs:
  test:
    continue-on-error: true
    strategy:
      matrix:
        os: [ macos-latest ]
        cxx: [ g++, clang++ ]
        stdlib: [ libstdc++, libc++ ]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v4
    - name: Install GNU Getopt on macOS
      if: matrix.os == 'macos-latest'
      run: brew install gnu-getopt
    - name: configure
      run: |
        if [[ ${{ runner.os }} == "macOS" ]]; then
          ./configure --with-cxx=${{ matrix.cxx }}
        else
          ./configure --with-cxx=${{ matrix.cxx }} --with-cxx-standard-library=${{ matrix.stdlib }}
        fi
    - name: build
      run: make
    - name: check
      run: make check
